In [30]:
import torch
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4
max_iters = 1000
# eval_interval = 2500
learning_rate = 3e-4
eval_iters = 250

cuda


In [31]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print(text[:200])
chars = sorted(set(text))
print(chars)
vocab_size = len(chars)

The Wonderful Wizard of Oz

by L. Frank Baum


This book is dedicated to my good friend & comrade
My Wife
L.F.B.


Contents

 Introduction
 Chapter I. The Cyclone
 Chapter II. The Council with the Mun
['\n', ' ', '!', '&', '(', ')', ',', '-', '.', '0', '1', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”']


In [32]:
#Tokenizer

#encoder - transforms an array into an integer
#decoder - transforsm the integer into an array

# If we work with a word level tokenizer then we have a ton of words and that's a lot of tokens
# But in this case we will have a smaller set to encode and decode
# if we have a subwork

string_to_int = { ch:i for i, ch in enumerate(chars)}
int_to_string = { i:ch for i, ch in enumerate(chars)}
encoder = lambda s:[string_to_int[c] for c in s]
decoder = lambda l: ''.join([int_to_string[i] for i in l])

print(encoder('hello'))
print(decoder(encoder('hello')))

[48, 45, 52, 52, 55]
hello


In [33]:
data = torch.tensor(encoder(text), dtype=torch.long)
print(data[:100])

tensor([34, 48, 45,  1, 37, 55, 54, 44, 45, 58, 46, 61, 52,  1, 37, 49, 66, 41,
        58, 44,  1, 55, 46,  1, 29, 66,  0,  0, 42, 65,  1, 26,  8,  1, 20, 58,
        41, 54, 51,  1, 16, 41, 61, 53,  0,  0,  0, 34, 48, 49, 59,  1, 42, 55,
        55, 51,  1, 49, 59,  1, 44, 45, 44, 49, 43, 41, 60, 45, 44,  1, 60, 55,
         1, 53, 65,  1, 47, 55, 55, 44,  1, 46, 58, 49, 45, 54, 44,  1,  3,  1,
        43, 55, 53, 58, 41, 44, 45,  0, 27, 65])


In [34]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) 
    print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix]) # This slicing operation extracts a portion of the data defined by the current index and the block size.
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
# print(x.shape)
print(x)
print('targets:')
print(y)

tensor([35171, 58822, 98943,  7381])
inputs:
tensor([[58, 45, 45, 59,  1, 47, 58, 45],
        [18, 55, 58, 55, 60, 48, 65,  1],
        [62, 45, 58, 65, 60, 48, 49, 54],
        [ 0, 45, 41, 58, 59,  1, 59, 60]], device='cuda:0')
targets:
tensor([[45, 45, 59,  1, 47, 58, 45, 63],
        [55, 58, 55, 60, 48, 65,  1, 60],
        [45, 58, 65, 60, 48, 49, 54, 47],
        [45, 41, 58, 59,  1, 59, 60, 49]], device='cuda:0')


In [35]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [36]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
# print(data[:100])

In [50]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        #This layer is used to map token indices to token embeddings. 
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) #learnable parameter 
   
    # we type it out because we want to know exactly what is going on
    def forward(self, index, targets=None): 
        logits = self.token_embedding_table(index) #It computes the token embeddings for the input index using the self.token_embedding_table.
        # "logits" typically refers to the raw, unnormalized scores or values that are produced by the output layer of a neural network before being passed through a softmax activation function.
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape # B - batch / T - time / C channel (vocab size)
            logits = logits.view(B*T, C)  # method is used to change the shape of the tensor while preserving its data
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets) # c
        return logits, loss
    
    def generate(self, index, max_new_tokens):
        # index is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self.forward(index)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C) in this case if shape was 1,1,72 it would take the probs of the 72
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            index = torch.cat((index, index_next), dim=1) # (B, T+1)
        return index

model = BigramLanguageModel(vocab_size)
m = model.to(device)
context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


!Ba,BCfTd&eCJ
Bs”(AiMQsPDGFQBD mB”CI.z.’;,uIENOGC—Ky”EgZ—’v—QTzBuI&Z‘JN&HqW0XoPQ
Jxhj
.z&MyHyKpOFc9,csRgENJaEX0gN—J1n&uz&iRuOLN!PZuCTizN-JtleIhQ,z’Rj’wF’KG)cP”N&gEdArEVo(w)clx&EA(:jn”G(qfZ(.’vg,he!Rb”
lOVEuz9WzW&uY”1mxsDkCmCkMEBy1YLr&PQRNP(XsIEIHrP1YZ!iVgyUxLQRg1clBpS!d
K“TpMRwoC;p‘ehJoWXZ’vBmpq’L!0o’,BYa
w—t’PJOZ!mRfbtqs?Ijq.uLG’K1sj;fp9t‘Q—‘
lCm—JUxxt;!RpSzuDKDbIc.R?!z9C TvJAv,,.&&QLGkYkBdQAZG.O
—J’Ze’vp??XPPWlN“y;f1YY‘s9tD:‘Bzsn”-.’vCXmXLjEE-;bIS!Ne.D‘WUkq.Tu?zX—a&
z”0n”My&!dKk,o.lDxQBsCnE”gN
